import argparse
from logic import generate_langchain_code
from writer import write_project_files

def get_static_files_content():
    """
    Defines the static content for the requirements and README files.
    """
    requirements_content = """langchain
langchain-openai
python-dotenv
"""

    readme_content = """# Auto-Generated LangChain Workflow

This project was automatically generated by the LangChain AutoPlanner Generator.

## 1. Setup

### a. Install Dependencies

First, you need to install the required Python libraries. Open your terminal in this directory and run:

```bash
pip install -r requirements.txt
```

### b. Set Up Environment Variables

This LangChain application gets all of its configuration from a `.env` file.

1.  Create a file named `.env` in this directory.
2.  Add your configuration to this file. See the example below for the required variables.

    ```
    # --- Required ---
    OPENAI_API_KEY="your_api_key_here"

    # --- Optional (defaults are provided in the script) ---
    API_BASE_URL="https://api.openai.com/v1"
    PRIMARY_MODEL="gpt-4"
    TEMPERATURE=0.7
    TOP_P=0.9
    MAX_TOKENS=2000
    ```

## 2. Run the Application

Once the setup is complete, you can run the LangChain workflow with the following command:

```bash
python main_langchain_flow.py
```
"""
    return requirements_content.strip() + '\\n', readme_content

def main():
    """
    The main entry point for the LangChain AutoPlanner Generator.
    """
    parser = argparse.ArgumentParser(description="Generate a LangChain project based on a user prompt.")
    parser.add_argument("--prompt", type=str, required=True, help="The user's requirement for the LangChain workflow.")
    args = parser.parse_args()

    print(f"Generating LangChain project for prompt: '{args.prompt}'")

    # 1. Generate the core LangChain code
    main_flow_code = generate_langchain_code(args.prompt)

    # 2. Get the content for the static files
    requirements, readme = get_static_files_content()

    # 3. Write all the files to the ./dist directory
    write_project_files(
        main_flow_code=main_flow_code,
        requirements=requirements,
        readme=readme
    )

if __name__ == "__main__":
    main()
